- try to run ejected code from orb

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,8 +3,8 @@
 # Check https://circleci.com/docs/2.0/language-javascript/ for more details
 #
 version: 2.1
-orbs:
-  cypress: cypress-io/cypress@1.8.0
+#orbs:
+#  cypress: cypress-io/cypress@1.8.0
 jobs:
   build:
     working_directory: ~/repo
@@ -41,6 +41,38 @@ jobs:
       - run:
           name: Run API Integration
           command: npm run ci:api
+  cypress/install:
+    docker:
+      - image: cypress/base:10
+    steps:
+      - checkout
+      - restore_cache:
+          keys:
+            - cache-v4-{{ .Branch }}-{{ checksum "package.json" }}
+      - run:
+          name: Check if package-lock.json exists
+          command: |
+            if [ ! -e ./package-lock.json ]; then
+              echo "The Cypress orb uses 'npm ci' to install 'node_modules', which requires a 'package-lock.json'."
+              echo "A 'package-lock.json' file was not found. Please run 'npm install' in your project,"
+              echo "and commit 'package-lock.json' to your repo."
+              exit 1
+            fi
+          working_directory: ~/repo
+      - run:
+          name: Verfy Cypress
+          command: npm run cy:verify
+          working_directory: ~/repo
+      - save_cache:
+          key: cache-v4-{{ .Branch }}-{{ checksum "package.json" }}
+          paths:
+            - ~/.npm
+            - ~/.cache
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project
+            - .cache/Cypress
 workflows:
   version: 2
   build_and_test:
@@ -50,13 +82,25 @@ workflows:
           requires:
             - build
       - cypress/install:
-          working_directory: ~/repo
           requires:
             - build
-      - cypress/run:
-          working_directory: ~/repo
-          cache-key: cache-v4-{{ .Branch }}-{{ checksum "package.json" }}
-          requires:
-            - cypress/install
-          start: npm run ci:ui
-          wait-on: 'http://localhost:8080'
+
+#workflows:
+#  version: 2
+#  build_and_test:
+#    jobs:
+#      - build
+#      - test_api:
+#          requires:
+#            - build
+#      - cypress/install:
+#          working_directory: ~/repo
+#          requires:
+#            - build
+#      - cypress/run:
+#          working_directory: ~/repo
+#          cache-key: cache-v4-{{ .Branch }}-{{ checksum "package.json" }}
+#          requires:
+#            - cypress/install
+#          start: npm run ci:ui
+#          wait-on: 'http://localhost:8080'
